%% Simple CPU Cooling System
%
% This example shows a simple CPU cooling system consists of a heat sink, a
% CPU fan, and fan controllers. The heat generated by the CPU is transferred
% to the heat sink by conduction and it is dissipated to the cooling air by
% forced convection mechanism. The heat sink is a parallel plate fin with
% rectangular fins between the plate fins. The CPU fan moves air across the
% heat sink by drawing air into the case grille from the outside and
% ejecting warm air from inside.
% The fan controller unit includes three control levels, representing a
% 3-speed switch, according to the CPU temperature. For lower CPU
% temperature, the fan speed is decreased and for higher temperature it is
% increased.
%
% Copyright 2018-2021 The MathWorks, Inc.


%% Model

open_system('SimpleCPUCoolingSystem')

set_param(find_system(bdroot,'FindAll','on','type','annotation','Tag','ModelFeatures'),'Interpreter','off');

%% CPU Board Subsystem

open_system('SimpleCPUCoolingSystem/CPU Board', 'force')

%% Fan Control Subsystem

open_system('SimpleCPUCoolingSystem/Fan Control', 'force')

%% Simulation Results from Scopes

set_param('SimpleCPUCoolingSystem/CPU board temperature', 'open','on');
sim('SimpleCPUCoolingSystem');

%%

set_param('SimpleCPUCoolingSystem/CPU board temperature', 'open','off');
%% Simulation Results from Simscape Logging
%%
%
% The plot below shows the volumetric flow rate - pressure rise
% characteristics of CPU fan.
%

SimpleCPUCoolingSystemPlot1FanCharacteristics;
%%
%
% The plots below show the volumetric flow rate through and pressure rise
% across the CPU fan.
%

SimpleCPUCoolingSystemPlot2FlowRate;

%%

